org: arnauddrain
app: function-test
service: function-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  updateCSV:
    handler: handler.updateCSV
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-plugin-typescript
